[package]
name = "keyring-core"
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
ssh-key.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
